// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLO1s_VTaTajiS4eFCHPsp3vyAYXLjygk',
    appId: '1:474383073336:web:8e0f136ad864aa5163a6cd',
    messagingSenderId: '474383073336',
    projectId: 'minderbrain-4bd55',
    authDomain: 'minderbrain-4bd55.firebaseapp.com',
    storageBucket: 'minderbrain-4bd55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPoj6g9UGqXSEwPM2k_g1w4jWq9em7iac',
    appId: '1:474383073336:android:7fa2c3ad9f8cae8963a6cd',
    messagingSenderId: '474383073336',
    projectId: 'minderbrain-4bd55',
    storageBucket: 'minderbrain-4bd55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuNB-8ygNqjhSkMo72VZ6Lv5pKTC3-DP4',
    appId: '1:474383073336:ios:0e5a6ebf754d168c63a6cd',
    messagingSenderId: '474383073336',
    projectId: 'minderbrain-4bd55',
    storageBucket: 'minderbrain-4bd55.appspot.com',
    iosClientId: '474383073336-bs0fo0nk2s9rqdgvkpq1ub4ko9gr9bin.apps.googleusercontent.com',
    iosBundleId: 'com.example.minderbrain',
  );
}
